ALTER TABLE `BotOutbox`
  ADD COLUMN `recipientUserId` INTEGER NULL,
  ADD COLUMN `houseId` INTEGER NULL,
  ADD COLUMN `accessKind` VARCHAR(16) NOT NULL DEFAULT 'NONE',
  ADD COLUMN `subjectId` INTEGER NULL;
