import { createHash, randomBytes } from "node:crypto";
import { mkdtemp, readFile, rm, unlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import sharp from "sharp";
import { expect, it } from "vitest";

import { createApp } from "./app.js";
import { createDocumentVersion, parseDocumentPayload, type DocumentPayload } from "./documents.js";
import { publicDocumentStatus } from "./workflow.js";
import { PrismaUserRepository } from "./repositories/prisma-user-repository.js";
import { createSignedMaxInitData } from "./test/helpers/max-init-data.js";

const token = "integration-test-bot-token";
const enabled = !!process.env.TEST_DATABASE_URL;

it.skipIf(!enabled)("runs inspection, issues, remediation, reinspection, act and bot verification through app.inject", async () => {
  process.env.DATABASE_URL = process.env.TEST_DATABASE_URL;
  process.env.MAX_BOT_NAME = "PriemkaDemoBot";
  process.env.MAX_WEBHOOK_SECRET = "test-webhook-secret-0925";
  const directory = await mkdtemp(join(tmpdir(), "priemka-workflow-test-"));
  process.env.MEDIA_DIR = join(directory, "media");
  process.env.DOCUMENTS_DIR = join(directory, "documents");
  const repository = new PrismaUserRepository();
  const db = repository.prisma;
  const key = randomBytes(6).readUIntBE(0, 6).toString().padStart(15, "0");
  const users = await Promise.all(["Chair", "Council A", "Council B", "Executor", "Foreign", "Admin", "Other Council", "Resident", "Pending Council", "Other Chair"].map((name, index) => db.user.create({ data: { maxUserId: `8${key}${index}`, firstName: name, lastName: "Demo", languageCode: "ru", isAdmin: index === 5, lastAuthDate: new Date(), lastSeenAt: new Date() } })));
  const house = await db.house.create({ data: { address: `Test house ${key}` } });
  const house2 = await db.house.create({ data: { address: `Second test house ${key}` } });
  await Promise.all(users.slice(0, 4).map((user, index) => db.houseMembership.create({ data: { houseId: house.id, userId: user.id, role: index === 0 ? "CHAIRMAN" : index === 3 ? "EXECUTOR" : "COUNCIL_MEMBER", status: "ACTIVE", executorCompanyName: index === 3 ? "Демо УК" : null } })));
  await db.houseMembership.create({ data: { houseId: house2.id, userId: users[0].id, role: "RESIDENT", status: "ACTIVE" } });
  await db.houseMembership.create({ data: { houseId: house.id, userId: users[4].id, role: "EXECUTOR", status: "ACTIVE" } });
  await db.houseMembership.create({ data: { houseId: house2.id, userId: users[6].id, role: "COUNCIL_MEMBER", status: "ACTIVE" } });
  await db.houseMembership.create({ data: { houseId: house.id, userId: users[7].id, role: "RESIDENT", status: "ACTIVE" } });
  await db.houseMembership.create({ data: { houseId: house.id, userId: users[8].id, role: "COUNCIL_MEMBER", status: "PENDING" } });
  await db.houseMembership.create({ data: { houseId: house2.id, userId: users[9].id, role: "CHAIRMAN", status: "ACTIVE" } });
  const work = await db.work.create({ data: { houseId: house.id, executorUserId: users[3].id, title: `Test work ${key}`, description: "Демо работа", category: "COMMON_AREAS", status: "NEW", executorName: "Демо УК" } });
  const template = await db.checklistTemplate.create({ data: { code: `TEST_${key}`, title: "Test template", category: "COMMON_AREAS", items: { create: [{ order: 1, title: "Пункт один", method: "VISUAL", sourceType: "INTERNAL" }, { order: 2, title: "Пункт два", method: "VISUAL", sourceType: "INTERNAL" }] } } });
  const wrongTemplate = await db.checklistTemplate.create({ data: { code: `WRONG_${key}`, title: "Other category", category: "ROOF", items: { create: [{ order: 1, title: "Кровля", method: "VISUAL", sourceType: "INTERNAL" }] } } });
  const app = await createApp({ config: { botToken: token, botName: "PriemkaDemoBot", maxInitDataMaxAgeSeconds: 3600, allowSelfRoleSwitch: true }, userRepository: repository, businessDb: db, logger: false, staticRoot: "/nonexistent" });
  const auth = (index: number) => ({ "x-max-init-data": createSignedMaxInitData(token, { user: `{"id":${users[index].maxUserId},"first_name":"${users[index].firstName}","last_name":"Demo","username":null,"language_code":"ru","photo_url":null}` }) });
  const call = (index: number, method: "GET" | "POST" | "PUT" | "PATCH", url: string, payload?: Record<string, unknown>) => app.inject({ method, url, headers: auth(index), ...(payload === undefined ? {} : { payload }) });
  const upload = async (index: number) => {
    const bytes = await sharp({ create: { width: 16, height: 16, channels: 3, background: { r: 20, g: 50, b: 80 } } }).png().toBuffer();
    const boundary = "workflow-test-boundary";
    const response = await app.inject({ method: "POST", url: "/api/media", headers: { ...auth(index), "content-type": `multipart/form-data; boundary=${boundary}` }, payload: Buffer.concat([Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="file"; filename="proof.png"\r\nContent-Type: image/png\r\n\r\n`), bytes, Buffer.from(`\r\n--${boundary}--\r\n`)]) });
    expect(response.statusCode).toBe(201);
    return response.json().id as number;
  };
  try {
    expect((await call(5, "GET", `/api/houses/${house.id}/works`)).statusCode).toBe(200);
    expect((await db.user.findUniqueOrThrow({ where: { id: users[5].id } })).lastHouseId).toBeNull();
    expect((await call(0, "GET", `/api/houses/${house.id}/works`)).statusCode).toBe(200);
    expect((await db.user.findUniqueOrThrow({ where: { id: users[0].id } })).lastHouseId).toBe(house.id);
    expect((await call(0, "GET", `/api/houses/${house2.id}/works`)).statusCode).toBe(200);
    expect((await call(0, "GET", "/api/me")).json().houses[0].id).toBe(house2.id);
    await db.houseMembership.update({ where: { houseId_userId: { houseId: house2.id, userId: users[0].id } }, data: { status: "PENDING" } });
    expect((await call(0, "GET", "/api/me")).json().houses[0].id).toBe(house.id);
    expect((await call(5, "GET", "/api/me")).json().houses).toEqual([]);
    expect((await call(4, "GET", `/api/houses/${house.id}/works`)).json().items).toEqual([]);
    expect((await call(0, "GET", "/api/checklist-templates")).json().items.some((item: { id: number }) => item.id === template.id)).toBe(true);
    expect((await call(0, "GET", `/api/houses/${house.id}/members?role=COUNCIL_MEMBER`)).json().items).toHaveLength(3);
    expect((await call(0, "POST", `/api/works/${work.id}/inspections`, { checklistTemplateId: template.id, assigneeUserId: users[1].id })).statusCode).toBe(409);
    expect((await call(3, "POST", `/api/works/${work.id}/submit-for-inspection`, {})).statusCode).toBe(200);
    expect((await call(0, "POST", `/api/works/${work.id}/inspections`, { checklistTemplateId: wrongTemplate.id, assigneeUserId: users[1].id })).statusCode).toBe(400);
    expect(await db.inspection.count({ where: { workId: work.id } })).toBe(0);
    expect((await db.work.findUniqueOrThrow({ where: { id: work.id } })).status).toBe("NEW");
    for (const index of [3, 4, 6, 7, 8]) expect((await call(0, "POST", `/api/works/${work.id}/inspections`, { checklistTemplateId: template.id, assigneeUserId: users[index].id })).statusCode).toBe(400);
    expect((await call(0, "POST", `/api/works/${work.id}/inspections`, { checklistTemplateId: template.id, assigneeUserIds: [users[1].id] })).statusCode).toBe(400);
    const created = await call(0, "POST", `/api/works/${work.id}/inspections`, { checklistTemplateId: template.id, assigneeUserId: users[1].id });
    expect(created.statusCode).toBe(201);
    expect((await db.work.findUniqueOrThrow({ where: { id: work.id } })).status).toBe("IN_REVIEW");
    const inspection = await db.inspection.findUniqueOrThrow({ where: { id: created.json().id }, include: { items: { orderBy: { order: "asc" } }, assignments: true } });
    await db.checklistTemplateItem.update({ where: { templateId_order: { templateId: template.id, order: 1 } }, data: { title: "Шаблон изменён" } });
    expect(inspection.assignments).toHaveLength(1);
    const first = inspection.assignments[0];
    expect((await call(1, "GET", "/api/me/inspection-assignments")).json()).toEqual(expect.objectContaining({ page: 1, limit: 20, total: 1 }));
    expect((await call(1, "GET", "/api/me/inspection-assignments?page=2&limit=1")).json()).toEqual({ items: [], page: 2, limit: 1, total: 1 });
    expect((await call(1, "GET", "/api/me/inspection-assignments?page=0")).statusCode).toBe(400);
    expect((await call(1, "GET", "/api/me/inspection-assignments?limit=101")).statusCode).toBe(400);
    expect((await call(1, "GET", `/api/inspection-assignments/${first.id}`)).json().checklist[0].title).toBe("Пункт один");
    expect((await call(5, "GET", `/api/inspection-assignments/${first.id}`)).json().actions).toEqual({ save: false, complete: false });
    expect((await call(5, "PUT", `/api/inspection-assignments/${first.id}/answers/${inspection.items[0].id}`, { result: "PASS" })).statusCode).toBe(404);
    expect((await call(5, "POST", `/api/inspection-assignments/${first.id}/complete`, {})).statusCode).toBe(404);
    expect((await call(2, "GET", `/api/inspection-assignments/${first.id}`)).statusCode).toBe(404);
    const item1 = inspection.items[0].id, item2 = inspection.items[1].id;
    expect((await call(1, "GET", `/api/inspection-assignments/${first.id}`)).json().checklist[0].rules.maxCommentLength).toBe(512);
    expect((await call(1, "PUT", `/api/inspection-assignments/${first.id}/answers/${item1}`, { result: "FAIL", comment: "x".repeat(513) })).statusCode).toBe(400);
    expect((await call(1, "PUT", `/api/inspection-assignments/${first.id}/answers/${item1}`, { result: "FAIL", comment: "x".repeat(512) })).statusCode).toBe(200);
    expect((await call(1, "PUT", `/api/inspection-assignments/${first.id}/answers/${item2}`, { result: "FAIL", comment: "", mediaIds: [] })).statusCode).toBe(400);
    expect((await call(1, "PUT", `/api/inspection-assignments/${first.id}/answers/${item1}`, { result: "FAIL", comment: "Дефект", mediaIds: [] })).statusCode).toBe(200);
    expect((await call(1, "PUT", `/api/inspection-assignments/${first.id}/answers/${item2}`, { result: "UNABLE_TO_CHECK", comment: "", mediaIds: [] })).statusCode).toBe(400);
    expect((await call(1, "POST", `/api/inspection-assignments/${first.id}/complete`, {})).statusCode).toBe(400);
    expect((await call(1, "PUT", `/api/inspection-assignments/${first.id}/answers/${item1}`, { result: "PASS" })).statusCode).toBe(200);
    expect((await db.inspectionAssignment.findUniqueOrThrow({ where: { id: first.id } })).status).toBe("IN_PROGRESS");
    expect((await call(1, "POST", `/api/inspection-assignments/${first.id}/complete`, {})).statusCode).toBe(400);
    expect((await call(1, "PUT", `/api/inspection-assignments/${first.id}/answers/${item2}`, { result: "UNABLE_TO_CHECK", comment: "Проверю позднее" })).statusCode).toBe(400);
    expect((await call(1, "POST", `/api/inspection-assignments/${first.id}/complete`, {})).statusCode).toBe(400);
    expect((await db.work.findUniqueOrThrow({ where: { id: work.id } })).status).toBe("IN_REVIEW");
    const before = await upload(1);
    const fivePhotos = [before, ...(await Promise.all(Array.from({ length: 4 }, () => upload(1))))];
    expect((await call(1, "PUT", `/api/inspection-assignments/${first.id}/answers/${item2}`, { result: "FAIL", mediaIds: fivePhotos })).statusCode).toBe(200);
    expect((await call(1, "PUT", `/api/inspection-assignments/${first.id}/answers/${item2}`, { result: "FAIL", mediaIds: [...fivePhotos, 999999] })).statusCode).toBe(400);
    expect((await call(1, "PUT", `/api/inspection-assignments/${first.id}/answers/${item2}`, { result: "FAIL", comment: "Дефект", mediaIds: [before] })).statusCode).toBe(200);
    expect((await call(1, "POST", `/api/inspection-assignments/${first.id}/complete`, {})).statusCode).toBe(200);
    const firstReport = await db.document.findUniqueOrThrow({ where: { inspectionId: inspection.id }, include: { versions: true } });
    expect(firstReport.versions).toHaveLength(1);
    const initialIssueCount = await db.issue.count({ where: { workId: work.id } });
    const initialHistoryCount = await db.workHistory.count({ where: { workId: work.id, event: "INSPECTION_COMPLETED" } });
    expect((await call(1, "POST", `/api/inspection-assignments/${first.id}/complete`, {})).statusCode).toBe(200);
    expect(await db.document.count({ where: { inspectionId: inspection.id } })).toBe(1);
    expect(await db.issue.count({ where: { workId: work.id } })).toBe(initialIssueCount);
    expect(await db.workHistory.count({ where: { workId: work.id, event: "INSPECTION_COMPLETED" } })).toBe(initialHistoryCount);
    expect((await call(1, "PUT", `/api/inspection-assignments/${first.id}/answers/${item2}`, { result: "PASS", comment: "Изменено" })).statusCode).toBe(409);
    expect((await db.inspectionAnswer.findUniqueOrThrow({ where: { assignmentId_checklistItemId: { assignmentId: first.id, checklistItemId: item2 } } })).result).toBe("FAIL");
    await unlink(join(process.env.DOCUMENTS_DIR!, firstReport.versions[0].storagePath));
    expect((await call(1, "POST", `/api/inspection-assignments/${first.id}/complete`, {})).statusCode).toBe(200);
    const restoredFirstReport = await db.documentVersion.findFirstOrThrow({ where: { documentId: firstReport.id }, orderBy: { version: "desc" } });
    expect((await readFile(join(process.env.DOCUMENTS_DIR!, restoredFirstReport.storagePath))).length).toBeGreaterThan(0);
    expect(await db.documentVersion.count({ where: { documentId: firstReport.id } })).toBe(1);
    expect((await db.work.findUniqueOrThrow({ where: { id: work.id } })).status).toBe("IN_PROGRESS");
    const issues = await call(3, "GET", `/api/works/${work.id}/issues`);
    expect(issues.json().items).toHaveLength(1);
    expect(issues.json()).toEqual(expect.objectContaining({ page: 1, limit: 20, total: 1 }));
    expect((await call(3, "GET", `/api/works/${work.id}/issues?page=2&limit=1`)).json()).toEqual({ items: [], page: 2, limit: 1, total: 1 });
    expect((await call(3, "GET", `/api/works/${work.id}/issues?limit=101`)).statusCode).toBe(400);
    expect((await call(3, "GET", `/api/me/issues?status=OPEN&houseId=${house.id}`)).json()).toEqual(expect.objectContaining({ page: 1, limit: 20, total: 1 }));
    expect((await call(3, "GET", `/api/me/issues?status=OPEN&houseId=${house.id}&page=2&limit=1`)).json()).toEqual({ items: [], page: 2, limit: 1, total: 1 });
    expect((await call(3, "GET", "/api/me/issues?page=0")).statusCode).toBe(400);
    expect((await call(4, "GET", `/api/works/${work.id}/issues`)).statusCode).toBe(404);
    expect((await call(4, "GET", "/api/me/issues")).json().items).toHaveLength(0);
    const issueId = issues.json().items[0].id as number;
    for (const index of [1, 7]) expect((await call(index, "POST", `/api/works/${work.id}/documents`, { type: "REASONED_REFUSAL" })).statusCode).toBe(403);
    expect((await call(5, "POST", `/api/works/${work.id}/documents`, { type: "REASONED_REFUSAL" })).statusCode).toBe(404);
    expect((await call(9, "POST", `/api/works/${work.id}/documents`, { type: "REASONED_REFUSAL" })).statusCode).toBe(404);
    expect((await call(5, "GET", `/api/works/${work.id}`)).json().actions.generateReasonedRefusal).toBe(false);
    const refusal = await call(0, "POST", `/api/works/${work.id}/documents`, { type: "REASONED_REFUSAL" });
    expect(refusal.statusCode).toBe(201);
    const secondRefusal = await call(0, "POST", `/api/works/${work.id}/documents`, { type: "REASONED_REFUSAL" });
    expect(secondRefusal.statusCode).toBe(201);
    expect(secondRefusal.json().id).not.toBe(refusal.json().id);
    expect(secondRefusal.json().version).toBe(1);
    expect((await call(1, "POST", `/api/documents/${refusal.json().id}/confirm`, {})).statusCode).toBe(403);
    expect(refusal.json().status).toBe("CONFIRMED");
    expect((await call(0, "POST", `/api/documents/${refusal.json().id}/confirm`, {})).statusCode).toBe(403);
    const after = await upload(3);
    expect((await call(4, "POST", `/api/issues/${issueId}/remediations`, { comment: "Исправлено", mediaIds: [after] })).statusCode).toBe(404);
    const remediation = await call(3, "POST", `/api/issues/${issueId}/remediations`, { comment: "Исправлено", mediaIds: [after] });
    expect(remediation.statusCode).toBe(201);
    expect((await call(1, "GET", `/api/me/reinspections?houseId=${house.id}&status=ASSIGNED`)).json()).toEqual(expect.objectContaining({ page: 1, limit: 20, total: 1 }));
    expect((await call(1, "GET", `/api/me/reinspections?houseId=${house.id}&status=ASSIGNED&page=2&limit=1`)).json()).toEqual({ items: [], page: 2, limit: 1, total: 1 });
    expect((await call(1, "GET", "/api/me/reinspections?limit=101")).statusCode).toBe(400);
    expect((await db.work.findUniqueOrThrow({ where: { id: work.id } })).status).toBe("WAITING");
    expect((await call(3, "GET", `/api/works/${work.id}`)).json().actions.reportRemediation).toBe(false);
    expect((await call(3, "POST", `/api/issues/${issueId}/remediations`, { comment: "Повтор", mediaIds: [after] })).statusCode).toBe(409);
    const cleanWork = await db.work.create({ data: { houseId: house.id, executorUserId: users[3].id, title: `Clean work ${key}`, description: "Без замечаний", category: "COMMON_AREAS", submittedForInspectionAt: new Date() } });
    const cleanCreated = await call(0, "POST", `/api/works/${cleanWork.id}/inspections`, { checklistTemplateId: template.id, assigneeUserId: users[2].id });
    expect(cleanCreated.statusCode).toBe(201);
    const cleanInspection = await db.inspection.findUniqueOrThrow({ where: { id: cleanCreated.json().id }, include: { items: true, assignments: true } });
    const cleanAssignmentId = cleanInspection.assignments[0].id;
    expect((await call(2, "PUT", `/api/inspection-assignments/${cleanAssignmentId}/answers/${cleanInspection.items[0].id}`, { result: "UNABLE_TO_CHECK", comment: "Проверю позднее" })).statusCode).toBe(400);
    expect((await call(2, "PUT", `/api/inspection-assignments/${cleanAssignmentId}/answers/${cleanInspection.items[1].id}`, { result: "PASS" })).statusCode).toBe(200);
    expect((await call(2, "POST", `/api/inspection-assignments/${cleanAssignmentId}/complete`, {})).statusCode).toBe(400);
    expect((await call(2, "PUT", `/api/inspection-assignments/${cleanAssignmentId}/answers/${cleanInspection.items[0].id}`, { result: "PASS" })).statusCode).toBe(200);
    expect((await call(2, "POST", `/api/inspection-assignments/${cleanInspection.assignments[0].id}/complete`, {})).statusCode).toBe(200);
    expect((await db.work.findUniqueOrThrow({ where: { id: cleanWork.id } })).status).toBe("WAITING");
    const recoveryWork = await db.work.create({ data: { houseId: house.id, executorUserId: users[3].id, title: `Recovery work ${key}`, description: "Проверка восстановления", category: "COMMON_AREAS", submittedForInspectionAt: new Date() } });
    const recoveryCreated = await call(0, "POST", `/api/works/${recoveryWork.id}/inspections`, { checklistTemplateId: template.id, assigneeUserId: users[2].id });
    expect(recoveryCreated.statusCode).toBe(201);
    const recoveryInspection = await db.inspection.findUniqueOrThrow({ where: { id: recoveryCreated.json().id }, include: { assignments: true, items: true } });
    for (const item of recoveryInspection.items) expect((await call(2, "PUT", `/api/inspection-assignments/${recoveryInspection.assignments[0].id}/answers/${item.id}`, { result: "PASS" })).statusCode).toBe(200);
    await db.inspectionAssignment.update({ where: { id: recoveryInspection.assignments[0].id }, data: { status: "COMPLETED", completedAt: new Date() } });
    await db.work.update({ where: { id: recoveryWork.id }, data: { status: "WAITING" } });
    await db.workHistory.create({ data: { workId: recoveryWork.id, event: "INSPECTION_COMPLETED", details: "Без замечаний" } });
    const emptyReport = await db.document.create({ data: { workId: recoveryWork.id, inspectionId: recoveryInspection.id, type: "INSPECTION_REPORT", title: "Отчёт о проверке" } });
    expect((await call(2, "POST", `/api/inspection-assignments/${recoveryInspection.assignments[0].id}/complete`, {})).statusCode).toBe(200);
    expect(await db.documentVersion.count({ where: { documentId: emptyReport.id } })).toBe(1);
    expect(await db.document.count({ where: { inspectionId: recoveryInspection.id } })).toBe(1);
    expect(await db.issue.count({ where: { workId: recoveryWork.id } })).toBe(0);
    expect(await db.workHistory.count({ where: { workId: recoveryWork.id, event: "INSPECTION_COMPLETED" } })).toBe(1);
    const multiWork = await db.work.create({ data: { houseId: house.id, executorUserId: users[3].id, title: `Multi issue work ${key}`, description: "Два замечания", category: "COMMON_AREAS", submittedForInspectionAt: new Date() } });
    const multiCreated = await call(0, "POST", `/api/works/${multiWork.id}/inspections`, { checklistTemplateId: template.id, assigneeUserId: users[1].id });
    expect(multiCreated.statusCode).toBe(201);
    const multiInspection = await db.inspection.findUniqueOrThrow({ where: { id: multiCreated.json().id }, include: { items: { orderBy: { order: "asc" } }, assignments: true } });
    const multiAssignmentId = multiInspection.assignments[0].id;
    for (const item of multiInspection.items) {
      const photoId = await upload(1);
      expect((await call(1, "PUT", `/api/inspection-assignments/${multiAssignmentId}/answers/${item.id}`, { result: "FAIL", comment: `Дефект ${item.order}`, mediaIds: [photoId] })).statusCode).toBe(200);
    }
    expect((await call(1, "POST", `/api/inspection-assignments/${multiAssignmentId}/complete`, {})).statusCode).toBe(200);
    const groupedReport = await db.document.findUniqueOrThrow({ where: { inspectionId: multiInspection.id }, include: { versions: true } });
    const groupedPayload = groupedReport.versions[0].payloadJson as unknown as DocumentPayload;
    expect(groupedPayload.photoGroups?.map((group) => group.title)).toEqual(multiInspection.items.map((item) => `Пункт ${item.order}. ${item.title} — Дефект ${item.order}`));
    expect(groupedPayload.photoGroups?.map((group) => group.photos.length)).toEqual([1, 1]);
    const multiIssues = await db.issue.findMany({ where: { workId: multiWork.id }, orderBy: { id: "asc" } });
    expect(multiIssues).toHaveLength(2);
    const firstAfterId = await upload(3);
    const firstMultiRemediation = await call(3, "POST", `/api/issues/${multiIssues[0].id}/remediations`, { comment: "Первое исправлено", mediaIds: [firstAfterId] });
    expect(firstMultiRemediation.statusCode).toBe(201);
    expect((await db.work.findUniqueOrThrow({ where: { id: multiWork.id } })).status).toBe("IN_PROGRESS");
    const secondAfterId = await upload(3);
    const secondMultiRemediation = await call(3, "POST", `/api/issues/${multiIssues[1].id}/remediations`, { comment: "Второе исправлено", mediaIds: [secondAfterId] });
    expect(secondMultiRemediation.statusCode).toBe(201);
    expect((await db.work.findUniqueOrThrow({ where: { id: multiWork.id } })).status).toBe("WAITING");
    expect((await call(1, "POST", `/api/reinspections/${firstMultiRemediation.json().reinspectionId}/complete`, { result: "RESOLVED" })).statusCode).toBe(200);
    const firstMultiReinspectionId = firstMultiRemediation.json().reinspectionId as number;
    const multiReinspectionHistoryCount = await db.workHistory.count({ where: { workId: multiWork.id, event: "REINSPECTION_COMPLETED" } });
    expect((await call(1, "POST", `/api/reinspections/${firstMultiReinspectionId}/complete`, { result: "NOT_RESOLVED", comment: "Не должно измениться" })).json().result).toBe("RESOLVED");
    const latePhoto = await upload(1);
    expect((await call(1, "POST", `/api/reinspections/${firstMultiReinspectionId}/complete`, { result: "NOT_RESOLVED", comment: "Не должно измениться", mediaIds: [latePhoto] })).json().result).toBe("RESOLVED");
    expect((await db.media.findUniqueOrThrow({ where: { id: latePhoto } })).reinspectionId).toBeNull();
    expect(await db.document.count({ where: { reinspectionId: firstMultiReinspectionId } })).toBe(1);
    expect(await db.workHistory.count({ where: { workId: multiWork.id, event: "REINSPECTION_COMPLETED" } })).toBe(multiReinspectionHistoryCount);
    const multiReport = await db.document.findUniqueOrThrow({ where: { reinspectionId: firstMultiReinspectionId }, include: { versions: true } });
    await unlink(join(process.env.DOCUMENTS_DIR!, multiReport.versions[0].storagePath));
    expect((await call(1, "POST", `/api/reinspections/${firstMultiReinspectionId}/complete`, { result: "RESOLVED" })).statusCode).toBe(200);
    expect(await db.documentVersion.count({ where: { documentId: multiReport.id } })).toBe(1);
    expect((await db.reinspection.findUniqueOrThrow({ where: { id: firstMultiReinspectionId } })).result).toBe("RESOLVED");
    expect((await db.work.findUniqueOrThrow({ where: { id: multiWork.id } })).status).toBe("WAITING");
    expect((await call(3, "GET", `/api/works/${multiWork.id}`)).json().actions.reportRemediation).toBe(false);
    expect((await call(1, "POST", `/api/reinspections/${secondMultiRemediation.json().reinspectionId}/complete`, { result: "NOT_RESOLVED", comment: "Остался дефект" })).statusCode).toBe(200);
    expect((await db.work.findUniqueOrThrow({ where: { id: multiWork.id } })).status).toBe("IN_PROGRESS");
    const retryAfterId = await upload(3);
    const retryMultiRemediation = await call(3, "POST", `/api/issues/${multiIssues[1].id}/remediations`, { comment: "Второе исправлено повторно", mediaIds: [retryAfterId] });
    expect(retryMultiRemediation.statusCode).toBe(201);
    expect((await call(1, "POST", `/api/reinspections/${retryMultiRemediation.json().reinspectionId}/complete`, { result: "RESOLVED" })).statusCode).toBe(200);
    expect((await db.work.findUniqueOrThrow({ where: { id: multiWork.id } })).status).toBe("WAITING");
    const reinspectionId = remediation.json().reinspectionId as number;
    expect((await db.reinspection.findUniqueOrThrow({ where: { id: reinspectionId } })).assigneeUserId).toBe(users[1].id);
    expect((await call(5, "GET", `/api/reinspections/${reinspectionId}`)).json().actions).toEqual({ complete: false });
    expect((await call(5, "POST", `/api/reinspections/${reinspectionId}/complete`, { result: "RESOLVED" })).statusCode).toBe(404);
    await db.reinspection.update({ where: { id: reinspectionId }, data: { status: "COMPLETED", result: "NOT_RESOLVED", comment: "Остался дефект", completedAt: new Date() } });
    await db.issue.update({ where: { id: issueId }, data: { status: "OPEN" } });
    await db.work.update({ where: { id: work.id }, data: { status: "IN_PROGRESS" } });
    await db.workHistory.create({ data: { workId: work.id, event: "REINSPECTION_COMPLETED", details: "NOT_RESOLVED" } });
    const emptyReinspectionReport = await db.document.create({ data: { workId: work.id, reinspectionId, type: "REINSPECTION_REPORT", title: "Отчёт о повторной проверке" } });
    expect((await call(1, "POST", `/api/reinspections/${reinspectionId}/complete`, { result: "NOT_RESOLVED", comment: "Остался дефект" })).statusCode).toBe(200);
    expect(await db.documentVersion.count({ where: { documentId: emptyReinspectionReport.id } })).toBe(1);
    expect(await db.document.count({ where: { reinspectionId } })).toBe(1);
    expect(await db.workHistory.count({ where: { workId: work.id, event: "REINSPECTION_COMPLETED" } })).toBe(1);
    expect((await db.work.findUniqueOrThrow({ where: { id: work.id } })).status).toBe("IN_PROGRESS");
    expect((await db.issue.findUniqueOrThrow({ where: { id: issueId } })).status).toBe("OPEN");
    expect((await call(3, "GET", `/api/works/${work.id}`)).json().actions.reportRemediation).toBe(true);
    const after2 = await upload(3);
    const remediation2 = await call(3, "POST", `/api/issues/${issueId}/remediations`, { comment: "Повторно исправлено", mediaIds: [after2] });
    expect(remediation2.statusCode).toBe(201);
    const remediationHistory = await db.remediation.findMany({ where: { issueId }, orderBy: { id: "asc" }, include: { media: true } });
    expect(remediationHistory.map((item) => item.comment)).toEqual(["Исправлено", "Повторно исправлено"]);
    expect(remediationHistory.map((item) => item.media.length)).toEqual([1, 1]);
    expect(remediationHistory[0].id).not.toBe(remediationHistory[1].id);
    expect((await call(1, "POST", `/api/reinspections/${remediation2.json().reinspectionId}/complete`, { result: "RESOLVED", comment: "Устранено" })).statusCode).toBe(200);
    expect((await db.work.findUniqueOrThrow({ where: { id: work.id } })).status).toBe("WAITING");
    expect((await db.issue.findUniqueOrThrow({ where: { id: issueId } })).status).toBe("RESOLVED");
    const reinspectionDocuments = await db.document.findMany({ where: { workId: work.id, type: "REINSPECTION_REPORT" }, include: { versions: true } });
    expect(reinspectionDocuments).toHaveLength(2);
    expect(new Set(reinspectionDocuments.map((item) => item.reinspectionId)).size).toBe(2);
    expect(reinspectionDocuments.every((item) => item.versions.length === 1 && item.versions[0].version === 1)).toBe(true);
    const raceWork = await db.work.create({ data: { houseId: house.id, executorUserId: users[3].id, title: `Double click work ${key}`, description: "Проверка одновременного создания акта", category: "COMMON_AREAS", status: "WAITING" } });
    await db.inspection.create({ data: { workId: raceWork.id, checklistTemplateId: template.id, templateVersion: template.version, createdByUserId: users[0].id, assignments: { create: { assigneeUserId: users[1].id, status: "COMPLETED", completedAt: new Date() } } } });
    const raceResponses = await Promise.all([
      call(3, "POST", `/api/works/${raceWork.id}/documents`, { type: "ACCEPTANCE_ACT" }),
      call(3, "POST", `/api/works/${raceWork.id}/documents`, { type: "ACCEPTANCE_ACT" }),
    ]);
    expect(raceResponses.map((response) => response.statusCode).sort()).toEqual([201, 409]);
    expect(await db.document.count({ where: { workId: raceWork.id, type: "ACCEPTANCE_ACT" } })).toBe(1);
    expect((await call(0, "POST", `/api/works/${work.id}/documents`, { type: "ACCEPTANCE_ACT" })).statusCode).toBe(403);
    const act = await call(3, "POST", `/api/works/${work.id}/documents`, { type: "ACCEPTANCE_ACT" });
    expect(act.statusCode).toBe(201);
    expect(await db.document.count({ where: { workId: work.id, type: "ACCEPTANCE_ACT" } })).toBe(1);
    expect((await call(3, "GET", `/api/works/${work.id}`)).json().actions.generateAcceptanceAct).toBe(false);
    const duplicateAct = await call(3, "POST", `/api/works/${work.id}/documents`, { type: "ACCEPTANCE_ACT" });
    expect(duplicateAct.statusCode).toBe(409);
    expect(duplicateAct.json().message).toContain("уже сформирован");
    expect(await db.document.count({ where: { workId: work.id, type: "ACCEPTANCE_ACT" } })).toBe(1);
    expect((await call(0, "POST", `/api/documents/${act.json().id}/confirm`, {})).statusCode).toBe(403);
    for (const index of [1, 7]) expect((await call(index, "POST", `/api/documents/${act.json().id}/confirm`, {})).statusCode).toBe(403);
    expect((await call(5, "POST", `/api/documents/${act.json().id}/confirm`, {})).statusCode).toBe(404);
    expect((await call(3, "POST", `/api/documents/${act.json().id}/confirm`, { userId: users[0].id })).statusCode).toBe(400);
    expect((await call(3, "POST", `/api/documents/${act.json().id}/confirm`, {})).json().status).toBe("FINAL");
    expect((await call(3, "POST", `/api/documents/${act.json().id}/confirm`, {})).json().status).toBe("FINAL");
    expect(await db.documentConfirmation.count({ where: { documentVersion: { documentId: act.json().id } } })).toBe(1);
    expect((await call(5, "POST", `/api/documents/${act.json().id}/confirm`, {})).statusCode).toBe(404);
    expect((await call(0, "POST", `/api/documents/${act.json().id}/confirm`, {})).json().status).toBe("CONFIRMED");
    expect((await db.work.findUniqueOrThrow({ where: { id: work.id } })).status).toBe("ACCEPTED");
    expect((await call(0, "POST", `/api/documents/${act.json().id}/confirm`, {})).json().status).toBe("CONFIRMED");
    expect((await call(3, "POST", `/api/documents/${act.json().id}/confirm`, {})).json().status).toBe("CONFIRMED");
    expect(await db.documentVersion.count({ where: { documentId: act.json().id } })).toBe(2);
    expect(await db.documentConfirmation.count({ where: { documentVersion: { documentId: act.json().id } } })).toBe(4);
    expect(await db.workHistory.count({ where: { workId: work.id, event: "ACCEPTANCE_CONFIRMED" } })).toBe(1);
    expect((await call(3, "POST", `/api/works/${work.id}/documents`, { type: "ACCEPTANCE_ACT" })).statusCode).toBe(409);
    const originalActVersion = await db.documentVersion.findUniqueOrThrow({ where: { documentId_version: { documentId: act.json().id, version: 1 } } });
    const oldDuplicate = await createDocumentVersion(db, work.id, "ACCEPTANCE_ACT", users[3].id, originalActVersion.payloadJson as unknown as DocumentPayload, "PriemkaDemoBot");
    await db.documentConfirmation.create({ data: { documentVersionId: oldDuplicate.id, userId: users[3].id, roleSnapshot: "EXECUTOR" } });
    expect((await call(3, "POST", `/api/documents/${oldDuplicate.documentId}/confirm`, {})).statusCode).toBe(409);
    expect((await call(0, "POST", `/api/documents/${oldDuplicate.documentId}/confirm`, {})).statusCode).toBe(409);
    expect(await db.documentConfirmation.count({ where: { documentVersionId: oldDuplicate.id } })).toBe(1);
    expect(await db.documentVersion.count({ where: { documentId: oldDuplicate.documentId } })).toBe(1);
    expect(await db.workHistory.count({ where: { workId: work.id, event: "ACCEPTANCE_CONFIRMED" } })).toBe(1);
    expect((await db.work.findUniqueOrThrow({ where: { id: work.id } })).status).toBe("ACCEPTED");
    const recoveryAct = await call(3, "POST", `/api/works/${cleanWork.id}/documents`, { type: "ACCEPTANCE_ACT" });
    expect(recoveryAct.statusCode).toBe(201);
    expect((await call(3, "POST", `/api/documents/${recoveryAct.json().id}/confirm`, {})).json().status).toBe("FINAL");
    const recoveryActInitial = await db.documentVersion.findUniqueOrThrow({ where: { documentId_version: { documentId: recoveryAct.json().id, version: 1 } } });
    await db.documentConfirmation.create({ data: { documentVersionId: recoveryActInitial.id, userId: users[0].id, roleSnapshot: "CHAIRMAN" } });
    expect(await db.documentVersion.count({ where: { documentId: recoveryAct.json().id } })).toBe(1);
    expect((await db.work.findUniqueOrThrow({ where: { id: cleanWork.id } })).status).toBe("WAITING");
    expect((await call(0, "POST", `/api/documents/${recoveryAct.json().id}/confirm`, {})).json().status).toBe("CONFIRMED");
    expect((await db.work.findUniqueOrThrow({ where: { id: cleanWork.id } })).status).toBe("ACCEPTED");
    expect(await db.documentVersion.count({ where: { documentId: recoveryAct.json().id } })).toBe(2);
    expect(await db.workHistory.count({ where: { workId: cleanWork.id, event: "ACCEPTANCE_CONFIRMED" } })).toBe(1);
    expect((await call(0, "POST", `/api/documents/${recoveryAct.json().id}/confirm`, {})).json().status).toBe("CONFIRMED");
    expect(await db.documentConfirmation.count({ where: { documentVersion: { documentId: recoveryAct.json().id } } })).toBe(4);
    const recoveryActFinal = await db.documentVersion.findUniqueOrThrow({ where: { documentId_version: { documentId: recoveryAct.json().id, version: 2 } } });
    await unlink(join(process.env.DOCUMENTS_DIR!, recoveryActFinal.storagePath));
    expect((await call(0, "POST", `/api/documents/${recoveryAct.json().id}/confirm`, {})).json().status).toBe("CONFIRMED");
    const repairedActFinal = await db.documentVersion.findUniqueOrThrow({ where: { id: recoveryActFinal.id } });
    expect((await readFile(join(process.env.DOCUMENTS_DIR!, repairedActFinal.storagePath))).length).toBeGreaterThan(0);
    expect(await db.documentVersion.count({ where: { documentId: recoveryAct.json().id } })).toBe(2);
    const stagedAct = await call(3, "POST", `/api/works/${recoveryWork.id}/documents`, { type: "ACCEPTANCE_ACT" });
    expect(stagedAct.statusCode).toBe(201);
    expect((await call(3, "POST", `/api/documents/${stagedAct.json().id}/confirm`, {})).json().status).toBe("FINAL");
    const stagedInitial = await db.documentVersion.findUniqueOrThrow({ where: { documentId_version: { documentId: stagedAct.json().id, version: 1 } }, include: { confirmations: true } });
    const stagedRepresentative = await db.documentConfirmation.create({ data: { documentVersionId: stagedInitial.id, userId: users[0].id, roleSnapshot: "CHAIRMAN" } });
    const stagedPayload = stagedInitial.payloadJson as unknown as DocumentPayload;
    const stagedFinal = await createDocumentVersion(db, recoveryWork.id, "ACCEPTANCE_ACT", users[0].id, { ...stagedPayload, confirmations: [
      { name: "Executor Demo", role: "EXECUTOR", at: stagedInitial.confirmations[0].confirmedAt.toISOString() },
      { name: "Chair Demo", role: "CHAIRMAN", at: stagedRepresentative.confirmedAt.toISOString() },
    ] }, "PriemkaDemoBot", { documentId: stagedAct.json().id });
    expect(stagedFinal.status).toBe("FINAL");
    const stagedConfirmation = await call(0, "POST", `/api/documents/${stagedAct.json().id}/confirm`, {});
    expect(stagedConfirmation.statusCode, stagedConfirmation.body).toBe(200);
    expect(stagedConfirmation.json().status).toBe("CONFIRMED");
    expect(await db.documentVersion.count({ where: { documentId: stagedAct.json().id } })).toBe(2);
    expect((await db.documentVersion.findUniqueOrThrow({ where: { id: stagedFinal.id } })).status).toBe("CONFIRMED");
    expect((await db.work.findUniqueOrThrow({ where: { id: recoveryWork.id } })).status).toBe("ACCEPTED");
    expect(await db.workHistory.count({ where: { workId: recoveryWork.id, event: "ACCEPTANCE_CONFIRMED" } })).toBe(1);
    const detail = await call(0, "GET", `/api/works/${work.id}`);
    const documentItems = detail.json().documents as { id: number; type: string; status: string; version: number }[];
    expect(documentItems.filter((document) => document.id === act.json().id)).toEqual([expect.objectContaining({ version: 2, status: "CONFIRMED" })]);
    expect(documentItems.filter((document) => document.type === "REASONED_REFUSAL").map((document) => document.id)).toEqual(expect.arrayContaining([refusal.json().id, secondRefusal.json().id]));
    expect(new Set(documentItems.map((document) => document.id)).size).toBe(documentItems.length);
    expect(JSON.stringify(detail.json())).not.toContain("storagePath");
    expect(JSON.stringify(detail.json())).not.toContain("sha256");
    const latest = await db.documentVersion.findFirstOrThrow({ where: { documentId: act.json().id }, orderBy: { version: "desc" } });
    const firstVersion = await db.documentVersion.findUniqueOrThrow({ where: { documentId_version: { documentId: act.json().id, version: 1 } } });
    expect(firstVersion.status).toBe("SUPERSEDED");
    expect(await readFile(join(process.env.DOCUMENTS_DIR!, firstVersion.storagePath))).toBeTruthy();
    const file = await app.inject({ method: "GET", url: `/doc/${latest.publicKey}.pdf` });
    expect(file.statusCode).toBe(200);
    expect(file.headers["content-type"]).toBe("application/pdf");
    expect(latest.publicKey).toMatch(/^[a-z0-9]{20}$/);
    expect(parseDocumentPayload(`doc_${latest.publicKey}`)).toBe(latest.publicKey);
    expect((await publicDocumentStatus(db, latest.publicKey)).message).toContain("Целостность файла: подтверждена");
    const path = join(process.env.DOCUMENTS_DIR!, latest.storagePath);
    const original = await readFile(path);
    expect(createHash("sha256").update(original).digest("hex")).toBe(latest.sha256);
    try { await writeFile(path, Buffer.from("corrupt")); expect((await publicDocumentStatus(db, latest.publicKey)).message).toContain("целостность файла не подтверждена"); const repaired = await app.inject({ method: "GET", url: `/doc/${latest.publicKey}.pdf` }); expect(repaired.statusCode).toBe(200); const repairedVersion = await db.documentVersion.findUniqueOrThrow({ where: { id: latest.id } }); expect(createHash("sha256").update(repaired.rawPayload).digest("hex")).toBe(repairedVersion.sha256); expect(repaired.rawPayload.toString()).not.toBe("corrupt"); }
    finally { await writeFile(path, original); }
    expect((await publicDocumentStatus(db, "a".repeat(40))).message).toBe("Документ не найден");
    const legacyKey = randomBytes(20).toString("hex");
    await db.documentVersion.create({ data: { documentId: act.json().id, version: 3, status: "FINAL", payloadJson: JSON.parse(JSON.stringify(latest.payloadJson)), sha256: latest.sha256, storagePath: latest.storagePath, publicKey: legacyKey, createdByUserId: users[3].id } });
    expect(parseDocumentPayload(`doc_${legacyKey}`)).toBe(legacyKey);
    expect((await app.inject({ method: "GET", url: `/doc/${legacyKey}.pdf` })).statusCode).toBe(200);
    const ownRole = (index: number, role: string, executorCompanyName?: string) => call(index, "PATCH", `/api/me/houses/${house.id}/membership`, { role, ...(executorCompanyName ? { executorCompanyName } : {}) });
    expect((await ownRole(0, "RESIDENT")).statusCode).toBe(200);
    expect((await ownRole(3, "CHAIRMAN")).statusCode).toBe(200);
    const soloWorkResponse = await call(3, "POST", `/api/houses/${house.id}/works`, { executorUserId: users[3].id, title: `Solo work ${key}`, description: "Один пользователь проходит сценарий", category: "COMMON_AREAS" });
    expect(soloWorkResponse.statusCode).toBe(201);
    const soloWorkId = soloWorkResponse.json().id as number;
    expect((await db.work.findUniqueOrThrow({ where: { id: soloWorkId } })).executorName).toBe("Демо УК");
    expect((await ownRole(3, "EXECUTOR", "Демо УК")).statusCode).toBe(200);
    expect((await call(3, "POST", `/api/works/${soloWorkId}/submit-for-inspection`, {})).statusCode).toBe(200);
    expect((await ownRole(3, "CHAIRMAN")).statusCode).toBe(200);
    const soloInspectionResponse = await call(3, "POST", `/api/works/${soloWorkId}/inspections`, { checklistTemplateId: template.id, assigneeUserId: users[3].id });
    expect(soloInspectionResponse.statusCode).toBe(201);
    const soloInspection = await db.inspection.findUniqueOrThrow({ where: { id: soloInspectionResponse.json().id }, include: { items: true, assignments: true } });
    expect((await ownRole(3, "COUNCIL_MEMBER")).statusCode).toBe(200);
    for (const item of soloInspection.items) expect((await call(3, "PUT", `/api/inspection-assignments/${soloInspection.assignments[0].id}/answers/${item.id}`, { result: "PASS" })).statusCode).toBe(200);
    expect((await call(3, "POST", `/api/inspection-assignments/${soloInspection.assignments[0].id}/complete`, {})).statusCode).toBe(200);
    const soloInspectionDocuments = await db.document.count({ where: { inspectionId: soloInspection.id } });
    expect((await ownRole(3, "EXECUTOR", "Демо УК")).statusCode).toBe(200);
    expect((await call(3, "POST", `/api/inspection-assignments/${soloInspection.assignments[0].id}/complete`, {})).json().status).toBe("COMPLETED");
    expect(await db.document.count({ where: { inspectionId: soloInspection.id } })).toBe(soloInspectionDocuments);
    const soloActResponse = await call(3, "POST", `/api/works/${soloWorkId}/documents`, { type: "ACCEPTANCE_ACT" });
    expect(soloActResponse.statusCode).toBe(201);
    const soloActId = soloActResponse.json().id as number;
    expect((await call(3, "POST", `/api/documents/${soloActId}/confirm`, {})).json().status).toBe("FINAL");
    expect((await ownRole(3, "CHAIRMAN")).statusCode).toBe(200);
    expect((await call(3, "POST", `/api/documents/${soloActId}/confirm`, {})).json().status).toBe("CONFIRMED");
    expect((await db.work.findUniqueOrThrow({ where: { id: soloWorkId } })).status).toBe("ACCEPTED");
    const soloVersions = await db.documentVersion.findMany({ where: { documentId: soloActId }, include: { confirmations: true } });
    expect(soloVersions.find((version) => version.status === "CONFIRMED")?.confirmations.map((item) => [item.userId, item.roleSnapshot])).toEqual(expect.arrayContaining([[users[3].id, "EXECUTOR"], [users[3].id, "CHAIRMAN"]]));
    const concurrentWork = await db.work.create({ data: { houseId: house.id, executorUserId: users[4].id, title: `Concurrent ${key}`, description: "Гонки workflow", category: "COMMON_AREAS", status: "IN_PROGRESS" } });
    const concurrentInspection = await db.inspection.create({ data: { workId: concurrentWork.id, checklistTemplateId: template.id, templateVersion: template.version, createdByUserId: users[3].id, items: { create: [{ order: 1, title: "Пункт A", method: "VISUAL", sourceType: "INTERNAL", commentRequiredOnFail: false, photoRequiredOnFail: false }, { order: 2, title: "Пункт B", method: "VISUAL", sourceType: "INTERNAL", commentRequiredOnFail: false, photoRequiredOnFail: false }] }, assignments: { create: { assigneeUserId: users[1].id, status: "COMPLETED", completedAt: new Date() } } }, include: { items: true, assignments: true } });
    const concurrentAnswers = await Promise.all(concurrentInspection.items.map((item) => db.inspectionAnswer.create({ data: { assignmentId: concurrentInspection.assignments[0].id, checklistItemId: item.id, result: "FAIL", comment: `Дефект ${item.order}` } })));
    const concurrentIssues = await Promise.all(concurrentAnswers.map((answer) => db.issue.create({ data: { workId: concurrentWork.id, inspectionAnswerId: answer.id, title: `Дефект ${answer.id}`, description: answer.comment! } })));
    const mediaA = await upload(4), mediaB = await upload(4);
    const sameIssue = await Promise.all([call(4, "POST", `/api/issues/${concurrentIssues[0].id}/remediations`, { comment: "Первое", mediaIds: [mediaA] }), call(4, "POST", `/api/issues/${concurrentIssues[0].id}/remediations`, { comment: "Второе", mediaIds: [mediaB] })]);
    expect(sameIssue.map((item) => item.statusCode).sort()).toEqual([201, 409]);
    expect(await db.remediation.count({ where: { issueId: concurrentIssues[0].id } })).toBe(1);
    expect(await db.reinspection.count({ where: { issueId: concurrentIssues[0].id } })).toBe(1);
    const otherMedia = await upload(4);
    const otherRemediation = await call(4, "POST", `/api/issues/${concurrentIssues[1].id}/remediations`, { comment: "Второй дефект", mediaIds: [otherMedia] });
    expect(otherRemediation.statusCode).toBe(201);
    const firstReinspectionId = sameIssue.find((item) => item.statusCode === 201)!.json().reinspectionId as number;
    const secondReinspectionId = otherRemediation.json().reinspectionId as number;
    const bothResults = await Promise.all([call(1, "POST", `/api/reinspections/${firstReinspectionId}/complete`, { result: "RESOLVED" }), call(1, "POST", `/api/reinspections/${secondReinspectionId}/complete`, { result: "NOT_RESOLVED", comment: "Осталось" })]);
    expect(bothResults.map((item) => item.statusCode)).toEqual([200, 200]);
    expect((await db.work.findUniqueOrThrow({ where: { id: concurrentWork.id } })).status).toBe("IN_PROGRESS");
    expect((await db.issue.findUniqueOrThrow({ where: { id: concurrentIssues[0].id } })).status).toBe("RESOLVED");
    expect((await db.issue.findUniqueOrThrow({ where: { id: concurrentIssues[1].id } })).status).toBe("OPEN");
    const competingRemediation = await db.remediation.create({ data: { issueId: concurrentIssues[1].id, executorUserId: users[4].id, comment: "Ещё раз" } });
    const competingReinspection = await db.reinspection.create({ data: { issueId: concurrentIssues[1].id, remediationId: competingRemediation.id, assigneeUserId: users[1].id } });
    const competingResults = await Promise.all([call(1, "POST", `/api/reinspections/${competingReinspection.id}/complete`, { result: "RESOLVED" }), call(1, "POST", `/api/reinspections/${competingReinspection.id}/complete`, { result: "NOT_RESOLVED", comment: "Ещё осталось" })]);
    const actualResult = (await db.reinspection.findUniqueOrThrow({ where: { id: competingReinspection.id } })).result;
    expect(competingResults.map((item) => item.statusCode), competingResults.map((item) => item.body).join(" | ")).toEqual([200, 200]);
    expect(competingResults.every((item) => item.json().result === actualResult)).toBe(true);
    const replayHistoryCount = await db.workHistory.count({ where: { workId: concurrentWork.id, event: "REINSPECTION_COMPLETED" } });
    expect((await ownRole(1, "EXECUTOR", "Демо УК")).statusCode).toBe(200);
    const replayAfterRoleSwitch = await call(1, "POST", `/api/reinspections/${firstReinspectionId}/complete`, { result: "NOT_RESOLVED", comment: "Повтор после смены роли" });
    expect(replayAfterRoleSwitch.statusCode).toBe(200);
    expect(replayAfterRoleSwitch.json().result).toBe("RESOLVED");
    expect(await db.document.count({ where: { reinspectionId: firstReinspectionId } })).toBe(1);
    expect(await db.workHistory.count({ where: { workId: concurrentWork.id, event: "REINSPECTION_COMPLETED" } })).toBe(replayHistoryCount);
    expect((await ownRole(1, "COUNCIL_MEMBER")).statusCode).toBe(200);
    const answerRaceWork = await db.work.create({ data: { houseId: house.id, executorUserId: users[4].id, title: `Answer race ${key}`, description: "Ответ и завершение", category: "COMMON_AREAS", status: "IN_REVIEW" } });
    const raceInspection = await db.inspection.create({ data: { workId: answerRaceWork.id, checklistTemplateId: template.id, templateVersion: template.version, createdByUserId: users[3].id, items: { create: [{ order: 1, title: "Race item", method: "VISUAL", sourceType: "INTERNAL", commentRequiredOnFail: false, photoRequiredOnFail: false }] }, assignments: { create: { assigneeUserId: users[1].id } } }, include: { items: true, assignments: true } });
    const raceAssignmentId = raceInspection.assignments[0].id, raceItemId = raceInspection.items[0].id;
    const answerAndComplete = await Promise.all([call(1, "PUT", `/api/inspection-assignments/${raceAssignmentId}/answers/${raceItemId}`, { result: "PASS" }), call(1, "POST", `/api/inspection-assignments/${raceAssignmentId}/complete`, {})]);
    expect(answerAndComplete[0].statusCode).toBe(200);
    expect([200, 400]).toContain(answerAndComplete[1].statusCode);
    if (answerAndComplete[1].statusCode === 400) expect((await call(1, "POST", `/api/inspection-assignments/${raceAssignmentId}/complete`, {})).statusCode).toBe(200);
    expect((await db.inspectionAssignment.findUniqueOrThrow({ where: { id: raceAssignmentId } })).status).toBe("COMPLETED");
    expect((await call(1, "PUT", `/api/inspection-assignments/${raceAssignmentId}/answers/${raceItemId}`, { result: "FAIL", comment: "Поздно" })).statusCode).toBe(409);
    const event = `{"update_type":"bot_started","timestamp":1,"chat_id":9007199254740993,"payload":"doc_${latest.publicKey}"}`;
    expect((await app.inject({ method: "POST", url: "/max/webhook", headers: { "content-type": "application/json", "x-max-bot-api-secret": "wrong" }, payload: event })).statusCode).toBe(401);
    expect((await app.inject({ method: "POST", url: "/max/webhook", headers: { "content-type": "application/json", "x-max-bot-api-secret": process.env.MAX_WEBHOOK_SECRET! }, payload: event })).statusCode).toBe(200);
    expect((await db.botOutbox.findFirstOrThrow({ orderBy: { id: "desc" } })).chatId).toBe("9007199254740993");
    const legacyEvent = `{"update_type":"bot_started","timestamp":2,"chat_id":9007199254740993,"payload":"doc_${legacyKey}"}`;
    expect((await app.inject({ method: "POST", url: "/max/webhook", headers: { "content-type": "application/json", "x-max-bot-api-secret": process.env.MAX_WEBHOOK_SECRET! }, payload: legacyEvent })).statusCode).toBe(200);
    expect((await db.botOutbox.findFirstOrThrow({ orderBy: { id: "desc" } })).publicKey).toBe(legacyKey);
  } finally {
    await app.close();
    await rm(directory, { recursive: true, force: true });
    delete process.env.MEDIA_DIR;
    delete process.env.DOCUMENTS_DIR;
    delete process.env.MAX_WEBHOOK_SECRET;
  }
}, 30_000);
